/**
 * @file sea_constraints.h
 * @author Aliaksandr Nekrashevich (aliaksandr.nekrashevich@queensu.ca)
 * @brief Implements SeaQDescriptor - the entity to generate constraints and bounds for the 
 * Lagrangian Relaxation based optimization function.
 * @copyright (c) Smith School of Business, 2023
 */
#pragma once

#include "gm_src/gm_interfaces.h"
#include "sea_gm_apply.h"

namespace sea {
namespace backend {

/**
 * @brief Object to generate constraints and bounds for 
 * the Lagrangian Relaxation optimization function.
 */
class SeaQDescriptor : public gm::IQDescriptor {
public:
    /**
     * @brief Constructor for SeaQDescriptor.
     * 
     * @param storage The storage with all relevant managers.
     * @param state The state of trajectory.
     * @param config Configuration for the LR backend.
     */
    SeaQDescriptor(
            ManagerStorage storage,
            const State& state,
            const LagrangianRelaxationBackendConfig& config)
        : storage(storage)
        , state(state)
        , config(config) {}
    /**
     * @brief Creates constraint functions from independent variables.
     * 
     * @param variables Vector with independent variables.
     * @return Vector with created constraints.
     */
    virtual std::vector<CppAD::AD<double>> makeConstraints(
            const std::vector<CppAD::AD<double>>& variables) const override;
    /**
     * @brief Sets lower and upper bounds for constraints generated by makeConstraints().
     * 
     * @param glower Lower bounds.
     * @param gupper Upper bounds.
     */
    virtual void initConstraintsLR(
            std::vector<double>* glower, std::vector<double>* gupper) const override;
    /**
     * @brief Sets lower and upper bounds for independent variables.
     * 
     * @param vlower Lower bounds.
     * @param vupper Upper bounds.
     */
    virtual void initBoundsLR(
            std::vector<double>* vlower, std::vector<double>* vupper) const override;
    /**
     * @brief Virtual destructor to ensure that C++ polymorphism works correctly.
     */
    virtual ~SeaQDescriptor() {};

private:
    /// @brief Storage with all relevant managers (InputData, InputLinks, etc.)
    const ManagerStorage storage;
    /// @brief The state of evaluation trajectory.
    const State state;
    /// @brief Configuration for the LR backend.
    const LagrangianRelaxationBackendConfig config;
};

} // namespace backend
} // namespace sea
